// src/error.h
//

#ifndef ERROR_H
#define ERROR_H

typedef enum {
  OK = 0,
  ERR_FILE_ALREADY_EXISTS,
  ERR_MAX_FILES_REACHED,
  ERR_NOT_ENOUGH_SPACE,
  ERR_FILE_NOT_FOUND,
  ERR_NO_MEMORY,
  ERR_CMD_EMPTY,
  ERR_CMD_UNKNOWN,
  ERR_CMD_NO_ARGUMENT,
} err_t;

#endif  // ERROR_H
